# Generated by Django 5.1.7 on 2025-04-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('category', '0001_initial'), ('category', '0002_rename_parent_category_parents')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parents', models.ManyToManyField(blank=True, null=True, related_name='children', to='category.category')),
            ],
        ),
    ]
